# Example configuration file

# Rest API, talks to dr.beaker
Rest API:
  Host: localhost
  Port: 8080
  Path: dr.beaker

# The station map maps names of stations (these names should equal the names we
# receive from the input channel) to positions in the circuit. The first station
# should be at position 0.
Station map:
  "01:00:00:00:00:01": 0
  "01:00:00:00:00:02": 100
  "01:00:00:00:00:03": 200
  "01:00:00:00:00:04": 300

# count-von-count will log all received input to a CSV file. The file name can
# be configured here.
CSV log: log.csv

# The criteria used for judging laps
Criteria:
  Samples treshold: 0
  Stations treshold: 3
  Speed treshold: 0
  # Speed limit: 10000000
  Time treshold: 0
  Distance treshold: 100

# Set of allowed mac addresses
Mac set:
  - "00:00:00:00:00:01"
  - "00:00:00:00:00:02"
  - "00:00:00:00:00:03"
  - "00:00:00:00:00:04"

# Port to listen on
Listen port: 9001

# Verbosity. Should be either: Debug, Info, Warn, Error
Verbosity: Info
