# Example configuration file

# Rest API, talks to dr.beaker
Rest API:
  Host: 10.1.2.35
  Port: 8080
  Path: dr.beaker

# The station map maps names of stations (these names should equal the names we
# receive from the input channel) to positions in the circuit. The first station
# should be at position 0.
Station map:
  Station-0: 0
  Station-1: 100
  Station-2: 200

# count-von-count will log all received input to a CSV file. The file name can
# be configured here.
CSV log: log.csv

# The criteria used for judging laps
Criteria:
  Samples treshold: 3
  Speed treshold: 5
  Speed limit: 30
  Time treshold: 20
  Distance treshold: 100

# Set of allowed mac addresses
Mac set:
  - 00:11:22:33:44:55:66
  - 00:11:22:33:44:55:67
  - 00:11:22:33:44:55:68

# Port to listen on
Listen port: 9001
