# Example configuration file

# Rest API, talks to dr.beaker
Rest API:
  Host: drb
  Port: 80
  Path: dr.beaker

# The station map maps names of stations (these names should equal the names we
# receive from the input channel) to positions in the circuit. The first station
# should be at position 0.
Stations:
  "00:21:91:F1:EA:0A":   0 # Our booth         (a0)
  "00:21:91:F1:F1:31":  80 # First bridge      (a1)
  "00:22:B0:D0:61:1F": 170 # First ING banner  (a2)
  "00:1C:F0:F1:F8:25": 250 # Second bridge     (a3)
  "00:22:B0:D0:61:26": 300 # Second ING banner (a4)

# count-von-count will log all received input to a CSV file. The file name can
# be configured here.
Replay log: log.csv

# The criteria used for judging laps
Criteria:
  # Minimum amount of samples
  Samples treshold: 8

  # See at least 3 of 8 stations
  Stations treshold: 3

  # Speed must be positive
  Speed treshold: 0

  # No speed limit
  # Speed limit: 10000000

  # Determined by rigorous experiments involving Jens and a bike
  Time treshold: 40

  # Distance seen: 200m
  Distance treshold: 200

  # Drop at least two stations when deciding on a lap
  Drop treshold: 100

# Set of allowed mac addresses
Macs:
  "20:11:02:15:01:34": Stick 1
  "20:11:02:15:01:50": Stick 2
  "20:11:02:15:01:51": Stick 3
  "20:11:02:15:01:67": Stick 4
  "20:11:02:15:01:87": Stick 5
  "20:11:02:15:01:80": Stick 6
  "20:11:02:15:01:77": Stick 7
  "20:11:02:15:01:90": Stick 8
  "20:11:02:15:01:56": Stick 9
  "20:11:02:15:01:73": Stick 10
  "00:11:72:14:01:98": Stick 11
  "20:11:02:15:01:75": Stick 12
  "20:11:02:15:01:83": Stick 13
  "20:11:02:15:02:00": Stick 14
  "20:11:02:15:01:19": Stick 15
  "20:11:02:15:01:42": Stick 16
  "20:11:02:15:01:79": Stick 17
  "20:11:02:15:01:15": Stick 18
  "20:11:02:15:01:93": Stick 19
  "20:11:02:15:01:17": Stick 20

# Port to listen on
Listen port: 9001

# Minimum value for RSSI data: lower values are ignored
RSSI treshold: -81

# Port for admin interface
Admin port: 80

# Verbosity. Should be either: Debug, Info, Warn, Error
Verbosity: Info
